"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-02(kqbm+jn35k+*q1ul=tkg$2q-6dzqo_*@i@(cg2fn&46^wbq'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',


    'django.contrib.humanize',
    'django.contrib.sitemaps',
    'django_otp',
    'django_crontab',
    'exchange',
    'master',
    'account',
    'currency',
    'customer',
    'wallet',
    'ticket',
    # 'qr_code',
    # 'http_file',
    # 'mathfilters',
    # 'pg_copy',
    # 'pwa',
    # 'import_export',
    # 'rest_framework',
    # 'rest_framework_simplejwt',
    # 'rest_framework_simplejwt.token_blacklist',



    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'myproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'my_db_name',
#         'USER': 'my_username',
#         'PASSWORD': 'my_password', 
#         'HOST': 'localhost',
#         'PORT': '5432',
#     }
# }

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

# TIME_ZONE = 'UTC'
TIME_ZONE = 'Asia/Tehran'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'static'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

USERMEDIA_URL = '/usermedia/'
USERMEDIA_ROOT = BASE_DIR / 'usermedia'

FILEMEDIA_URL = '/filemedia/'
FILEMEDIA_ROOT =  BASE_DIR / "filemedia"

ICON_URL = '/icon/'
ICON_ROOT = BASE_DIR / 'icon'

PODCAST_URL = '/podcast/'
PODCAST_ROOT = BASE_DIR / 'podcast'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

PG_COPY_BACKUP_PATH = 'db_backup'

CRONJOBS = [


    # Activate 



    ('*/1 * * * *', 'exchange.cron.currency_buySell_check'),
    # ('*/1 * * * *', 'exchange.cron.'),
    # ('*/10 * * * *', 'exchange.cron.'),

    # ('0 */8 * * *', 'exchange.cron.'),
    # ('*/3 * * * *', 'exchange.cron.'),
    # ('*/2 * * * *', 'exchange.cron.'),   

    ('*/1 * * * *', 'exchange.cron.check_withdraw_irt'), 
    # ('30 3 * * *', 'exchange.cron.'), 
    # ('30 3 * * *', 'exchange.cron.'), 
    
    # ('5 4 * * *', 'exchange.cron.'), 

    # ('*/5 * * * *', 'exchange.cron.'),
    ('*/1 * * * *', 'exchange.cron.gold_price_check'),
    ('*/1 * * * *', 'exchange.cron.handly_price_check'),

    # ('*/15 * * * *', 'exchange.cron.'),
    ('*/1 * * * *', 'exchange.cron.physical_delivery_confirmation_check'), 
    ('*/5 * * * *', 'exchange.cron.check_connection_getway_physical_delivery'), 
    ('0 10 * * *', 'exchange.cron.check_reminder_for_physical_delivery'), 



    # ('0 */1 * * *', 'exchange.cron.'),
    # ('10 */2 * * *', 'exchange.cron.'),
    # ('0 0 */1 * *', 'exchange.cron.'),
 

    # ('*/5 * * * *', 'exchange.cron.'),
    
    # ('*/10 * * * *', 'exchange.cron.'), 

    # ('0 */24 * * *', 'exchange.cron.'),  
    # ('*/2 * * * *', 'exchange.cron.'), 
    # ('*/5 * * * *', 'exchange.cron.'), 

    ('*/1 * * * *', 'exchange.cron.check_daily_buysell'),
    ('*/1 * * * *', 'exchange.cron.check_heirs'),


    ('*/1 * * * *', 'exchange.cron.currency_buySell_price_requests_check'),
    ('*/1 * * * *', 'exchange.cron.currency_buySell_time_requests_check'),
    ('*/1 * * * *', 'exchange.cron.currency_buySell_cancel_requests_check'),

    ('*/1 * * * *', 'exchange.cron.last_gold_price_log_check'),
    ('*/1 * * * *', 'exchange.cron.check_expire_auto_orders'),

    # Activate 





]

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
